#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
unsigned int m;
cout<<"Enter the number of Month : ";
cin>>m;
if (m==1)
{
cout<<"January";
}
else if (m==2)
{
cout<<"February";
}
else if (m==3)
{
cout<<"March";
}
else if (m==4)
{
cout<<"April";
}
else if (m==5)
{
cout<<"May";
}
else if (m==6)
{
cout<<"June";
}
else if (m==7)
{
cout<<"July";
}
else if (m==8)
{
cout<<"August";
}
else if (m==9)
{
cout<<"September";
}
else if (m==10)
{
cout<<"October";
}
else if (m==11)
{
cout<<"November";
}
else if (m==12)
{
cout<<"December";
}
else
{
cout<<"Invalid Number, Please Enter Between 1 to 12";
}
getch();
}